

# Introduction {#intro}

`r if(identical(gitbook_on, FALSE))knitr::asis_output("This report is available as pdf and as an online [interactive report](https://newgraphenvironment.github.io/fish_passage_skeena_2021_reporting/) at https://newgraphenvironment.github.io/fish_passage_skeena_2021_reporting/. We recommend viewing online as the web-hosted html version contains more features and is more easily navigable.")` 


`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

This report builds on reporting from the spring of 2021 which can be referenced [here](https://newgraphenvironment.github.io/fish_passage_bulkley_2020_reporting/).  The work presented is currently in draft form for partner and stakeholder engagement purposes, contains errors and will change over time. 

<br>


The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 




